name = "TimeSeriesFunk"
uuid = "dea839fd-53b0-4e05-9f56-2c9dc6ecca94"
authors = ["georgeg <georgegi86@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
